# Generated by Django 3.1.11 on 2021-10-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0047_auto_20211027_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='callpower',
            name='share_email',
            field=models.CharField(blank=True, help_text='Share Progress id for email button, including the sp_... prefix', max_length=20),
        ),
        migrations.AddField(
            model_name='callpower',
            name='share_facebook',
            field=models.CharField(blank=True, help_text='Share Progress id for facebook button, including the sp_... prefix', max_length=20),
        ),
        migrations.AddField(
            model_name='callpower',
            name='share_link',
            field=models.URLField(blank=True, editable=False, help_text='Link that will be put in share button', max_length=1024),
        ),
        migrations.AddField(
            model_name='callpower',
            name='share_link_text',
            field=models.CharField(blank=True, default='Share this', editable=False, help_text='Text content of the share button', max_length=20),
        ),
        migrations.AddField(
            model_name='callpower',
            name='share_twitter',
            field=models.CharField(blank=True, help_text='Share Progress id for twitter button, including the sp_... prefix', max_length=20),
        ),
    ]
