# Generated by Django 3.1.11 on 2021-10-28 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0048_auto_20211028_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callpower',
            name='share_link',
        ),
        migrations.RemoveField(
            model_name='callpower',
            name='share_link_text',
        ),
    ]
